### ISSUE TITLE
Support for Encrypted Passwords Appears to be Broken

### ISSUE THREAD

**Issue by kevinsarsen** [shyiko/servers-maven-extension#4]
I am receiving this error when using encrypted passwords in my settings.xml file:

```
[ERROR] Failed to expose settings.servers.*: Illegal group reference -> [Help 1]
org.apache.maven.MavenExecutionException: Failed to expose settings.servers.*
        at com.github.shyiko.sme.ServersExtension.afterProjectsRead(ServersExtension.java:97)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:266)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.lang.IllegalArgumentException: Illegal group reference
        at java.util.regex.Matcher.appendReplacement(Matcher.java:857)
        at com.github.shyiko.sme.ServersExtension.decryptInlinePasswords(ServersExtension.java:106)
        at com.github.shyiko.sme.ServersExtension.afterProjectsRead(ServersExtension.java:74)
        ... 14 more

```
Contents of POM:
```
<build>
        <extensions>
            <extension>
                <groupId>com.github.shyiko.servers-maven-extension</groupId>
                <artifactId>servers-maven-extension</artifactId>
                <version>1.3.0</version>
            </extension>
        </extensions>
...
```
If I escape the curly braces with an '\', the error goes away, but then the strings are not recognized as encrypted passwords.

Any help would be appreciated.

**Comment by shyiko** [comment]
Hi @kevinsarsen. Is you password enclosed in {} (like https://github.com/shyiko/servers-maven-extension/issues/2#issuecomment-97416338)? Also, can you please specify Maven version? Thanks.

**Comment by kevinsarsen** [comment]
Hi @shyiko,

Yes, the encrypted password is enclosed in the curly braces and my Maven version is 3.3.9.

I forked your project and did some debugging. It appears that the issue occurs when the password contains special, reserved regex characters such as '$'. I'm thinking these will need to be escaped, but I'm not sure yet how that will impact usage of the passwords elsewhere in the POM. I'm working on testing this out.

Thanks for your quick response!

**Comment by shyiko** [comment]
Any updates?

**Comment by azzazzel** [comment]
HI, I know this is an old report but I just hit the exact same issue! 
My password was encrypted with `mvn -ep`. It is enclosed in `{}` and only contains letters, digits, `/`, `+` and  `=`.

**Comment by azzazzel** [comment]
OK initially misunderstood @kevinsarsen but he is right! The issue is with special characters in the __decrypted__ password. Exception is thrown If it contains `$` since it is a group symbol in regex's replacement parameter.
